version: '3.8'

services:
  facial_gesture_recognition:
    image: facial_gesture_recognition
    container_name: facial_gesture_recognition
    working_dir: /root/facial_gesture_recognition
    build: ./server
    ports: 
      - "40005:40005"
    command: python3 -u server.py
    volumes:
      - ./output:/root/facial_gesture_recognition/output
      - ./media:/root/facial_gesture_recognition/media

  # client:
  #   image: 
  #   container_name: client
  #   build: ./client
  #   devices:
  #     - /dev/video0:/dev/video0
    